os:
  editPreset: "nvim-remote"
gui:
  showRandomTip: false
  disableStartupPopups: true
  showBottomLine: true
  showCommandLog: false
  nerdFontsVersion: "3"
  showFileIcons: true
  border: single
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
git:
  paging:
    colorArg: always
    pager: delta --features lazygit
keybinding:
  # Use neovim for writing commit messages by default
  files:
    commitChanges: C
    commitChangesWithEditor: c
  commits:
    openLogMenu: <c-g>
# Do not prompt after git commands
promptToReturnFromSubprocess: false
notARepository: "quit"
