return {

  "williamboman/mason.nvim",
  version = "1.11.0",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "css-lsp",
      "html-lsp",
      "vue-language-server",
      "js-debug-adapter",
      "eslint-lsp",
      "prettierd",
      "astro-language-server",
      "sqlfluff",
      "elixir-ls",
      "hadolint",
      "checkmake",
      "emmet-language-server",
      "js-debug-adapter",
      "flake8",
      "pyright",
      "debugpy",
      "ruff",
      "isort",
      "black",
      "erb-formatter",
      "erb-lint",
      "solargraph",
    },
  },
}
