##########################################################
# Sample .aider.conf.yml
# This file lists *all* the valid configuration entries.
# Place in your home dir, or at the root of your git repo.
##########################################################

# Note: You can only put OpenAI and Anthropic API keys in the yaml
# config file. Keys for all APIs can be stored in a .env file
# https://aider.chat/docs/config/dotenv.html

##################
# Alias

alias:
  - "fast:gpt-4o-mini"
  - "smart:o3-mini"

#############
# Main model:

## Specify the model to use for the main chat
model: smart

##################
# Output settings:

## Use colors suitable for a dark terminal background (default: False)
dark-mode: true

## Use colors suitable for a light terminal background (default: False)
#light-mode: false

## Enable/disable pretty, colorized output (default: True)
#pretty: true

## Enable/disable streaming responses (default: True)
#stream: true

## Set the color for user input (default: #00cc00)
#user-input-color: "#00cc00"

## Set the color for tool output (default: None)
tool-output-color: "#cdd6f4"

## Set the color for tool error messages (default: #FF2222)
#tool-error-color: "#FF2222"

## Set the color for tool warning messages (default: #FFA500)
#tool-warning-color: "#FFA500"

## Set the color for assistant output (default: #0088ff)
#assistant-output-color: "#0088ff"

## Set the color for the completion menu (default: terminal's default text color)
completion-menu-color: "#cdd6f4"

## Set the background color for the completion menu (default: terminal's default background color)
completion-menu-bg-color: "#1e1e2e"

## Set the color for the current item in the completion menu (default: terminal's default background color)
completion-menu-current-color: "#f38ba8"

## Set the background color for the current item in the completion menu (default: terminal's default text color)
completion-menu-current-bg-color: "#585b70"

## Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light, or a Pygments builtin style, see https://pygments.org/styles for available themes)
code-theme: monokai

## Show diffs when committing changes (default: False)
show-diffs: true

###############
# Git settings:

## Enable/disable looking for a git repo (default: True)
#git: true

# Enable/disable auto commit of LLM changes (default: True)
auto-commits: false

# Attribute aider commits in the git committer name (default: True)
attribute-committer: false

# Enable/disable git pre-commit hooks with --no-verify (default: False)
git-commit-verify: true

# Commit all pending changes with a suitable commit message, then exit
commit: false

# Perform a dry run without modifying files (default: False)
#dry-run: false

# Enable/disable watching files for ai coding comments (default: False)
#watch-files: false

########################
# Fixing and committing:

## Lint and fix provided files, or dirty files if none provided
#lint: false

## Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)
#lint-cmd: xxx
## Specify multiple values like this:
#lint-cmd:
#  - xxx
#  - yyy
#  - zzz

############
# Analytics:

## Permanently disable analytics
analytics-disable: true

############
# Upgrading:

## Check for new aider versions on launch
check-update: false

## Upgrade aider to the latest version from PyPI
upgrade: false

########
# Modes:

## Run aider in your browser (default: False)
#gui: false

## Enable automatic copy/paste of chat between aider and web UI (default: False)
#copy-paste: false

## Apply the changes from the given file instead of running the chat (debug)
#apply: xxx

## Do all startup activities then exit before accepting user input (debug)
#exit: false

## Print the repo map and exit (debug)
#show-repo-map: false

## Print the system prompts and exit (debug)
#show-prompts: false

## Use VI editing mode in the terminal (default: False)
vim: true

## Enable verbose output
#verbose: false

## Enable/disable multi-line input mode with Meta-Enter to submit (default: False)
#multiline: false

## Enable/disable terminal bell notifications when LLM responses are ready (default: False)
notifications: true
